name: Backend Deploy (Lambda)

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "alembic/**"
      - "lambda_handler.py"
      - "requirements.txt"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Lambda package (Amazon Linux)
        run: |
          mkdir package

          docker run --rm \
            --platform=linux/amd64 \
            -v "$PWD":/var/task \
            --entrypoint /bin/bash \
            public.ecr.aws/lambda/python:3.10 \
            -c "pip install -r requirements.txt -t package"

          cp -r app package/
          cp lambda_handler.py package/

          cd package
          zip -r ../function.zip .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name flow-manager \
            --zip-file fileb://function.zip
